# Audio and Video Feature Fusion 

## Media Pipe Files

In [2]:
#import libraies
import numpy as np
import pandas as pd

In [4]:
# Load the .npy Audio file with extracted features for one audio file
audio = np.load('trial_lie_001_000_audio.npy')

# Display the data
print(audio)

[[ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 ...
 [-0.00698853  0.00115967]
 [-0.00628662  0.0010376 ]
 [-0.00579834  0.00094604]]


In [11]:
#convereting to dataframes
df = pd.DataFrame(data, columns=['x', 'y'])
df

x         y
0       0.000000  0.000000
1       0.000000  0.000000
2       0.000000  0.000000
3       0.000000  0.000000
4       0.000000  0.000000
...          ...       ...
185656 -0.007294  0.000916
185657 -0.007233  0.001190
185658 -0.006989  0.001160
185659 -0.006287  0.001038
185660 -0.005798  0.000946

[185661 rows x 2 columns]

In [18]:
# Load the .npy extracted features for one video file
video = np.load('trial_lie_001_000_coord.npy')
print(video)

[[ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.55135888  0.3718549  -0.01029661]
 [ 0.53652966  0.34174782 -0.00771655]
 [ 0.55495477  0.33811989 -0.00859307]
 [ 0.5587343   0.34038976 -0.00962396]
 [ 0.56097913  0.33801949 -0.00712045]
 [ 0.56121397  0.33849752 -0.00610122]
 [ 0.56385988  0.3385663  -0.00536199]
 [ 0.54799747  0.34762371 -0.00546369]
 [ 0.54575145  0.34488618 -0.00601773]
 [ 0.5467298   0.34295064 -0.00539485]
 [ 0.53997105  0.34412119 -0.00467093]
 [ 0.5354448   0.34433258 -0.00490647]
 [ 0.53154755  0.3458069  -0.00534169]
 [ 0.52905345  0.34578228 -0.00601253]
 [ 0.52765238  0.3472558  -0.00565695]
 [ 0.52364284  0.35012934 -0.00694074]
 [ 0.52011734  0.35006335 -0.00699198]
 [ 0.51966012  0.35109606 -0.00746177]
 [ 0.51850682  0.35336718 -0.00822651]
 [ 0.51967657  0.35553065 -0.01006473]
 [ 0.52124304  0.35616198 -0.0106131 ]
 [ 0.52382654  0.35647142 -0.01095332]
 [ 0.52823699  0.35741726

In [12]:
df_coord = pd.DataFrame(data1, columns=['x', 'y','z'])
df_coord

x         y         z
0    0.000000  0.000000  0.000000
1    0.000000  0.000000  0.000000
2    0.000000  0.000000  0.000000
3    0.551359  0.371855 -0.010297
4    0.536530  0.341748 -0.007717
..        ...       ...       ...
121  0.549267  0.375751 -0.008832
122  0.558418  0.373193 -0.005865
123  0.560253  0.373025 -0.006625
124  0.559474  0.373045 -0.005775
125  0.563968  0.369726 -0.005184

[126 rows x 3 columns]

In [16]:
label= np.load('trial_lie_001_000_label.npy')
print(label)

[1]


In [25]:
pip install librosa

     |████████████████████████████████| 252 kB 2.6 MB/s eta 0:00:01
     |████████████████████████████████| 405 kB 41.4 MB/s eta 0:00:01
     |████████████████████████████████| 377 kB 2.4 MB/s eta 0:00:01
     |████████████████████████████████| 1.2 MB 24.8 MB/s eta 0:00:01
     |████████████████████████████████| 60 kB 13.7 MB/s eta 0:00:01
     |████████████████████████████████| 19.8 MB 19.3 MB/s eta 0:00:01
     |████████████████████████████████| 17.6 MB 2.7 MB/s eta 0:00:01
  Created wheel for audioread: filename=audioread-3.0.0-py3-none-any.whl size=23694 sha256=2ec161a0473bae85af5ed237c2998077e9b9b8064d9bd39a72ce5c8111ee743c
  Stored in directory: /Users/shreya/Library/Caches/pip/wheels/0a/ed/be/49df2538fca496690a024a4374455584d65c2afd6fc3d6e9c7
Successfully built audioread
  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.1
    Uninstalling numpy-1.20.1:
      Successfully uninstalled numpy-1.20.1
  Attempting uninstall: typing-extensions
    Found existing

### Method 1 - Concatenation

This code loads audio and video features from two separate .npy files, normalizes each feature set by subtracting the mean and dividing by the standard deviation, and then concatenates the two feature sets into a single array using NumPy's concatenate() function.
The flatten() method is called on each normalized feature set before concatenating them to create a 1D array, as the concatenate() function requires both input arrays to have the same number of dimensions along all axes except the concatenation axis.
The resulting fused feature is a 1D array that contains both the normalized audio and video features. This can be used for further processing or modeling, such as feeding the feature set into a machine learning algorithm for classification or regression.

In [2]:
import numpy as np

# Load audio and video features from .npy files
audio_feature = np.load("trial_lie_001_000_audio.npy")
video_feature = np.load("trial_lie_001_000_coord.npy")

# Normalize audio and video features
audio_norm = (audio_feature - np.mean(audio_feature)) / np.std(audio_feature)
video_norm = (video_feature - np.mean(video_feature)) / np.std(video_feature)

# Concatenate normalized audio and video features
fused_feature = np.concatenate((audio_norm.flatten(), video_norm.flatten()))
print(fused_feature)

# Save the fused feature as a .csv file
np.savetxt("fused_feature_concatenation.csv", fused_feature, delimiter=",")


# Use the fused feature for further processing or modeling
print("Shape of fused feature:", fused_feature.shape)

[-0.02736425 -0.02736425 -0.02736425 ...  1.17970071  0.33855153
 -1.28496893]
Shape of fused feature: (371700,)


In [31]:
#convert it to a dataframe for better read.
fused_df = pd.DataFrame(fused_feature)
fused_df

0
0      -0.027364
1      -0.027364
2      -0.027364
3      -0.027364
4      -0.027364
...          ...
371695  0.352926
371696 -1.287527
371697  1.179701
371698  0.338552
371699 -1.284969

[371700 rows x 1 columns]

### Method 2 - PCA 

The code loads the visual features from a numpy array file and standardizes the data using StandardScaler. Then, it performs PCA to reduce the dimensionality of the visual features, keeping only the minimum number of principal components required to explain the variance in the data. The number of principal components is determined by min(visual_features_scaled.shape[0], visual_features_scaled.shape[1]), which ensures that the number of principal components does not exceed the number of samples or features in the input data.

Ensure that the number of rows in the two feature arrays match: Since PCA reduces the dimensionality of the input data, the resulting feature arrays may have different numbers of rows. To concatenate the two feature arrays, the code determines the minimum number of rows between the two arrays using min_rows, and then slices both arrays to keep only the first min_rows rows. This ensures that the two arrays have the same number of rows and can be concatenated along the horizontal axis.

In [3]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# Load and preprocess the audio features
audio_features = np.load('trial_lie_001_000_audio.npy')  # assuming numpy array format
audio_scaler = StandardScaler()
audio_features_scaled = audio_scaler.fit_transform(audio_features)
n_components_audio = min(audio_features_scaled.shape[0], audio_features_scaled.shape[1])
audio_pca = PCA(n_components=n_components_audio)  # reduce dimensionality to n_components_audio using PCA
audio_features_pca = audio_pca.fit_transform(audio_features_scaled)

# Load and preprocess the visual features
visual_features = np.load('trial_lie_001_000_coord.npy')  # assuming numpy array format
visual_scaler = StandardScaler()
visual_features_scaled = visual_scaler.fit_transform(visual_features)
n_components_visual = min(visual_features_scaled.shape[0], visual_features_scaled.shape[1])
visual_pca = PCA(n_components=n_components_visual)  # reduce dimensionality to n_components_visual using PCA
visual_features_pca = visual_pca.fit_transform(visual_features_scaled)

# Ensure that the number of rows in the two feature arrays match
min_rows = min(audio_features_pca.shape[0], visual_features_pca.shape[0])
audio_features_pca = audio_features_pca[:min_rows, :]
visual_features_pca = visual_features_pca[:min_rows, :]

# Concatenate the audio and visual features
fused_features = np.concatenate((audio_features_pca, visual_features_pca), axis=1)

np.savetxt("fused_feature_PCA.csv", fused_features, delimiter=",")

print(fused_features)


[[ 1.26666474e+00 -1.24070050e+00  9.73313224e+00 -1.18766745e+00
  -1.87002644e-02]
 [ 1.26666474e+00 -1.24070050e+00  9.73313224e+00 -1.18766745e+00
  -1.87002644e-02]
 [ 1.26666474e+00 -1.24070050e+00  9.73313224e+00 -1.18766745e+00
  -1.87002644e-02]
 [ 1.26666474e+00 -1.24070050e+00 -5.21253122e-01 -1.05450888e-01
   7.99646317e-02]
 [ 1.26666474e+00 -1.24070050e+00  4.80355553e-01  6.08421211e-01
   1.91014516e-01]
 [ 1.26666474e+00 -1.24070050e+00  1.94461669e-01  3.84462470e-01
   4.39685473e-01]
 [ 1.26666474e+00 -1.24070050e+00 -8.44947890e-02  4.51178508e-02
   5.06621289e-01]
 [ 1.26666474e+00 -1.24070050e+00  4.77012634e-01  9.48936815e-01
   3.92071858e-01]
 [ 1.26666474e+00 -1.24070050e+00  6.94825807e-01  1.31911667e+00
   3.21196543e-01]
 [ 1.26666474e+00 -1.24070050e+00  8.38077846e-01  1.60078494e+00
   2.92777165e-01]
 [ 1.26666474e+00 -1.24070050e+00  8.31068131e-01  1.51077164e+00
   5.66433675e-02]
 [ 1.26666474e+00 -1.24070050e+00  7.54725199e-01  1.28667715e+00

In [42]:
print("Shape of fused feature:", fused_features.shape)

Shape of fused feature: (126, 5)


### Method 3 - Early Fusion

In early fusion technique instead of plain stacking of the values and arrays, the data here is combined on raw values and combines it along a particular axis and adjusting the dimesionality of the arrays for eliminating a set of values in order to reshape the arrays to match. Early Fusion of pre-extracted features can capture the correlation between different modalities more explicitly and may be able to leverage this correlation for better performance compared to concatenation.

In [4]:
import numpy as np

# load the audio and video features from the .npy files
audio_features = np.load('trial_lie_001_000_audio.npy')
video_features = np.load('trial_lie_001_000_coord.npy')

# check the shapes of the input arrays
print(audio_features.shape)
print(video_features.shape)

# if the shapes don't match, try to reshape the arrays to match
if audio_features.shape[0] != video_features.shape[0]:
    if audio_features.shape[0] < video_features.shape[0]:
        video_features = video_features[:audio_features.shape[0], :]
    else:
        audio_features = audio_features[:video_features.shape[0], :]

# concatenate the audio and video features horizontally
combined_features = np.hstack((audio_features, video_features))

# perform normalization on the combined features
mean = np.mean(combined_features, axis=0)
std = np.std(combined_features, axis=0)
std += 1e-10 # add a small constant value to avoid division by zero
combined_features = (combined_features - mean) / std

print(combined_features)

np.savetxt("fused_feature_earlyfusion.csv", combined_features, delimiter=",")


# use the combined features for downstream tasks, such as classification
labels = np.load('trial_lie_001_000_label.npy')
#Shape
print("Shape of combined feature:", combined_features.shape)

(185661, 2)
(126, 3)
[[ 0.00000000e+00  0.00000000e+00 -6.35333921e+00 -6.29015931e+00
   4.02662912e+00]
 [ 0.00000000e+00  0.00000000e+00 -6.35333921e+00 -6.29015931e+00
   4.02662912e+00]
 [ 0.00000000e+00  0.00000000e+00 -6.35333921e+00 -6.29015931e+00
   4.02662912e+00]
 [ 0.00000000e+00  0.00000000e+00  3.10093821e-01  2.36723332e-01
  -3.70166075e-01]
 [ 0.00000000e+00  0.00000000e+00  1.30875698e-01 -2.91723068e-01
   7.31555555e-01]
 [ 0.00000000e+00  0.00000000e+00  3.53551837e-01 -3.55401260e-01
   3.57268916e-01]
 [ 0.00000000e+00  0.00000000e+00  3.99229253e-01 -3.15560085e-01
  -8.29334439e-02]
 [ 0.00000000e+00  0.00000000e+00  4.26359087e-01 -3.57163575e-01
   9.86100654e-01]
 [ 0.00000000e+00  0.00000000e+00  4.29197268e-01 -3.48773096e-01
   1.42132536e+00]
 [ 0.00000000e+00  0.00000000e+00  4.61174340e-01 -3.47565787e-01
   1.73698629e+00]
 [ 0.00000000e+00  0.00000000e+00  2.69469664e-01 -1.88588176e-01
   1.69355662e+00]
 [ 0.00000000e+00  0.00000000e+00  2.4232542

### Method 4 - Attention Feature Fusion 

In [66]:
pip install keras 


     |████████████████████████████████| 1.7 MB 1.2 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [68]:
pip install tensorflow

     |████████████████████████████████| 244.3 MB 28 kB/s  eta 0:00:011    |██████                          | 46.1 MB 11.7 MB/s eta 0:00:17
     |████████████████████████████████| 439 kB 5.4 MB/s eta 0:00:01
     |████████████████████████████████| 1.6 MB 11.9 MB/s eta 0:00:01
     |████████████████████████████████| 8.2 MB 14.2 MB/s eta 0:00:01
     |████████████████████████████████| 6.0 MB 11.0 MB/s eta 0:00:01
     |████████████████████████████████| 57 kB 8.2 MB/s eta 0:00:01
     |████████████████████████████████| 25.0 MB 4.1 MB/s eta 0:00:01
     |████████████████████████████████| 980 kB 6.8 MB/s eta 0:00:01
     |████████████████████████████████| 65 kB 7.1 MB/s eta 0:00:01
     |████████████████████████████████| 126 kB 10.2 MB/s eta 0:00:01
     |████████████████████████████████| 93 kB 167 kB/s eta 0:00:01
     |████████████████████████████████| 3.5 MB 8.9 MB/s eta 0:00:01
     |████████████████████████████████| 177 kB 10.3 MB/s eta 0:00:01
     |████████████████████████████████| 78

#### Approach 1 

The attention mechanism for both audio and video features is implemented using a fully-connected layer with a 'tanh activation' followed by a 'softmax layer' to compute the attention weights. The attention weights are then used to weight the input features and compute the final attentional features. Finally, the attentional audio and video features are concatenated and passed through a dense layer with softmax activation to perform the classification task. Note that the code assumes that the number of classes is defined as num_classes.

In [ ]:
from keras.layers import Input, Dense, LSTM, Concatenate, Permute, Reshape, Lambda, Multiply, Add, Dot
from keras.models import Model
from keras import backend as K

# Load audio and video features from numpy files
audio_features = np.load('trial_lie_001_000_audio.npy')
video_features = np.load('trial_lie_001_000_coord.npy')

# Define input layers for audio and video features
audio_input = Input(shape=(None, audio_features.shape[1]))
video_input = Input(shape=(None, video_features.shape[1]))

# Define attention mechanism for audio features
audio_attention = Dense(1, activation='tanh')(audio_input)
audio_attention = Permute((2, 1))(audio_attention)
audio_attention = Reshape((-1,))(audio_attention)
audio_attention = Lambda(lambda x: x / np.sqrt(audio_features.shape[1]))(audio_attention)
audio_attention = Dense(audio_features.shape[1], activation='softmax')(audio_attention)
audio_attention = Reshape((1, -1))(audio_attention)
audio_attention = Multiply()([audio_input, audio_attention])
audio_attention = Lambda(lambda x: K.sum(x, axis=1))(audio_attention)

# Define attention mechanism for video features
video_attention = Dense(1, activation='tanh')(video_input)
video_attention = Permute((2, 1))(video_attention)
video_attention = Reshape((-1,))(video_attention)
video_attention = Lambda(lambda x: x / np.sqrt(video_features.shape[1]))(video_attention)
video_attention = Dense(video_features.shape[1], activation='softmax')(video_attention)
video_attention = Reshape((1, -1))(video_attention)
video_attention = Multiply()([video_input, video_attention])
video_attention = Lambda(lambda x: K.sum(x, axis=1))(video_attention)

# Concatenate attentional audio and video features
merged_features = Concatenate()([audio_attention, video_attention])
print(merged_features)

# Define output layer for classification or regression
output_layer = Dense(num_classes, activation='softmax')(merged_features)

# Define model with input and output layers
model = Model(inputs=[audio_input, video_input], outputs=output_layer)
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train model on data
model.fit([audio_features, video_features], labels, epochs=10, batch_size=32)


In [ ]:
import numpy as np
# Load new audio and video features from numpy files
new_audio_features = np.load('trial_lie_001_000_audio.npy')
new_video_features = np.load('trial_lie_001_000_coord.npy')

# Generate predictions for new features
predictions = model.predict([new_audio_features, new_video_features])

# Print the predicted probabilities for each class
print(predictions)


#### Approach2 

In [8]:
import numpy as np

# define calculate_attention_weights function
def calculate_attention_weights(features):
    # calculate mean and standard deviation for each feature
    mean = np.mean(features, axis=0)
    std = np.std(features, axis=0)

    # calculate attention weights based on inverse variance
    inv_var = 1 / (std ** 2 + 1e-6)  # add a small value to avoid division by zero
    weights = inv_var / np.sum(inv_var)

    return weights

# load audio and video features
audio_features = np.load('trial_lie_001_000_audio.npy')
video_features = np.load('trial_lie_001_000_coord.npy')

# reshape audio_features to have the same number of columns as video_features
audio_weights = audio_weights.reshape(1, -1) # reshape to (1, 126)
video_weights = video_weights.reshape(1, -1) # reshape to (1, 126)

# calculate attention weights for audio and video features
audio_weights = calculate_attention_weights(audio_features)
video_weights = calculate_attention_weights(video_features)

# normalize attention weights
audio_weights = audio_weights / np.sum(audio_weights)
video_weights = video_weights / np.sum(video_weights)

# apply attention pooling to combine audio and video features
combined_features = audio_weights.T * audio_features + video_weights.T * video_features

# save combined features
np.save('combined_features.npy', combined_features)


ValueError: operands could not be broadcast together with shapes (185661,2) (126,3) 

In [ ]:
# import numpy as np

# def fuse_features(audio_files, video_files):
#     """
#     Fuse audio and video features from a list of .npy files.

#     Args:
#         audio_files (list): List of strings representing paths to .npy files containing audio features.
#         video_files (list): List of strings representing paths to .npy files containing video features.

#     Returns:
#         numpy.ndarray: Fused feature matrix of shape (num_samples, num_features).
#     """
#     num_samples = len(audio_files)

#     # Initialize fused feature matrix
#     fused_features = np.zeros((num_samples, 744*39+3*512**3))

#     # Loop over each sample and fuse its audio and video features
#     for i in range(num_samples):
#         # Load audio and video features from .npy files
#         audio_feature = np.load(audio_files[i])
#         video_feature = np.load(video_files[i])

#         # Normalize audio and video features
#         audio_norm = (audio_feature - np.mean(audio_feature)) / np.std(audio_feature)
#         video_norm = (video_feature - np.mean(video_feature)) / np.std(video_feature)

#         # Concatenate normalized audio and video features
#         fused_feature = np.concatenate((audio_norm.flatten(), video_norm.flatten()))

#         # Add fused feature to the feature matrix
#         fused_features[i,:] = fused_feature

#     return fused_features
